#!/usr/bin/env ruby

require "ginny"
require "optparse"
options = {}

optparse = OptionParser.new do |opts|
  opts.banner = "Usage: ginny [options] [path]"
  opts.on("-h", "--help", "Display this screen") do
    puts(opts)
    exit(0)
  end
  opts.on("-v", "--version", "Display version information") do
    puts("Ginny version #{Ginny::VERSION}")
    exit(0)
  end
end

optparse.parse!

ARGV.each do |f|
  Ginny::Class.create(Ginny.load_file(f)).generate()
end
